export const PERSONAL_PROJECTS = [
    {
        id: 1,
        type: "personal" as const,
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
        title: "GenSiteAI",
        subtitle: "An AI-powered website generator where users enter prompts to generate fully functional websites. Iterative re-prompting lets users refine UI and output.",
        technologies: ["Next.js", "AI", "Tailwind CSS", "Refinement Engine"],
        github: "https://github.com/niks-nikhil-anand/GenSiteAI",
        demo: "https://gensite-ai.vercel.app",
    },
    {
        id: 2,
        type: "personal" as const,
        image: "https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?w=800&q=80",
        title: "LiveDocs",
        subtitle: "A real-time collaborative document editing platform with live commenting and reactions to boost productivity.",
        technologies: ["React", "Socket.io", "Node.js", "Redis"],
        github: "#",
        demo: "#",
    },
    {
        id: 3,
        type: "personal" as const,
        image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&q=80",
        title: "Chat-with-pdf-RAG",
        subtitle: "A Retrieval-Augmented Generation (RAG) application built with Next.js, Express, Docker, BullMQ, and QdrantDB that enables users to upload PDFs and interact with their content.",
        technologies: ["Next.js", "Express", "Docker", "QdrantDB", "BullMQ"],
        github: "#",
        demo: "#",
    },
    {
        id: 4,
        type: "personal" as const,
        image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&q=80",
        title: "AI-Voice-Interview-Platform",
        subtitle: "A voice-based interview practice platform where users interact with an AI interviewer and receive detailed scores and feedback.",
        technologies: ["Next.js", "Web Speech API", "OpenAI", "Node.js"],
        github: "#",
        demo: "#",
    },
    {
        id: 5,
        type: "personal" as const,
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
        title: "AI_SAAS-Sketch-to-Build",
        subtitle: "An AI-powered SaaS that converts design sketches into fully functional, production-ready applications.",
        technologies: ["Next.js", "Tailwind CSS", "Computer Vision", "AI"],
        github: "#",
        demo: "#",
    },
    {
        id: 6,
        type: "personal" as const,
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80",
        title: "AI-Resume-Analyzer",
        subtitle: "An intelligent resume evaluation tool that provides detailed feedback on strengths, weaknesses, and improvement areas with applicant tracking system (ATS) emulation.",
        technologies: ["React", "Python", "NLP", "ATS Algorithms"],
        github: "#",
        demo: "#",
    }
];

export const FREELANCE_PROJECTS = [
    {
        id: 7,
        type: "freelance" as const,
        image: "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=800&q=80",
        title: "Donation Website",
        subtitle: "A modern donation platform for non-profits with secure payment gateway integration.",
        technologies: ["Next.js", "Razorpay", "PostgreSQL"],
        client: "NGO Partners",
        duration: "2 months",
        demo: "https://legal257.com",
        github: "#",
    },
    {
        id: 8,
        type: "freelance" as const,
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        title: "Legal257 - Finance",
        subtitle: "Comprehensive financial and legal consultancy platform for legal professionals.",
        technologies: ["React", "Express", "Node.js", "MongoDB"],
        client: "Legal257",
        duration: "4 months",
        demo: "https://legal257.com",
        github: "#",
    },
    {
        id: 9,
        type: "freelance" as const,
        image: "https://images.unsplash.com/photo-1505751172107-597d5a4d4b91?w=800&q=80",
        title: "Swastify - Doctor Appointment",
        subtitle: "Full-scale doctor appointment booking system with real-time slot management.",
        technologies: ["Next.js", "Firebase", "Realtime DB"],
        client: "Swastify",
        duration: "6 months",
        demo: "https://swasthify.com",
        github: "#",
    }
];
